apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: muxcore
resources:
  - namespace.yaml
  - core-config.yaml
  - core.yaml
  - api-rest.yaml
  - auth-local.yaml
  - database-sqlite.yaml
  - secrets-file.yaml
  - encryption-aesgcm.yaml
  - policies.yaml
  - health-monitor.yaml
  - admin-ui.yaml
labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: muxcore
    includeSelectors: false
