apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets-file
  labels:
    app.kubernetes.io/name: secrets-file
    app.kubernetes.io/part-of: muxcore
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: secrets-file
  template:
    metadata:
      labels:
        app.kubernetes.io/name: secrets-file
        app.kubernetes.io/part-of: muxcore
    spec:
      containers:
        - name: secrets-file
          image: git.zem.systems/muxcore/secrets-file:v0.5.7
          imagePullPolicy: IfNotPresent
          env:
            - name: MUXCORE_GRPC_ADDR
              value: muxcored:9090
            - name: MUXCORE_MODULE_ID
              value: secrets-file
            - name: MUXCORE_INSECURE_DISABLE_TLS
              value: "true"
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: 15m
              memory: 32Mi
            limits:
              cpu: 250m
              memory: 128Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: secrets-file-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: secrets-file-data
  labels:
    app.kubernetes.io/name: secrets-file
    app.kubernetes.io/part-of: muxcore
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
