#!/usr/bin/env bash
# Path A registry smoke helpers — curl + containerized grpcurl (no host Go / siblings).
set -euo pipefail

REGISTRY_SMOKE_COMPOSE_FILE="${MUXCORE_COMPOSE_FILE:-docker-compose.registry.yml}"
# Pinned (not :latest) so the gate is reproducible; override with MUXCORE_GRPCURL_IMAGE.
REGISTRY_SMOKE_GRPCURL_IMAGE="${MUXCORE_GRPCURL_IMAGE:-docker.io/fullstorydev/grpcurl:v1.9.3}"
REGISTRY_SMOKE_CURL_IMAGE="${MUXCORE_CURL_IMAGE:-docker.io/curlimages/curl:8.5.0}"
REGISTRY_SMOKE_ALPINE_IMAGE="${MUXCORE_ALPINE_IMAGE:-docker.io/library/alpine:3.21}"

registry_smoke_root="${REGISTRY_SMOKE_ROOT:-${ROOT:-}}"

# Container runtime / compose indirection: MUXCORE_CONTAINER_CLI=podman,
# MUXCORE_COMPOSE="podman compose" (or "podman-compose") for docker-less hosts.
registry_smoke_cli() {
  # shellcheck disable=SC2086 # MUXCORE_CONTAINER_CLI may carry flags
  ${MUXCORE_CONTAINER_CLI:-docker} "$@"
}

# MUXCORE_COMPOSE_EXTRA_FILES: space-separated override files (relative to this
# repo or absolute) layered on the registry compose, e.g. docker-compose.dev.yml
# for the insecure dev loop; the restore drill must see the same services.
registry_smoke_compose() {
  local -a files=(-f "${registry_smoke_root}/${REGISTRY_SMOKE_COMPOSE_FILE}")
  local f
  for f in ${MUXCORE_COMPOSE_EXTRA_FILES:-}; do
    [[ "$f" == /* ]] || f="${registry_smoke_root}/$f"
    files+=(-f "$f")
  done
  # shellcheck disable=SC2086 # MUXCORE_COMPOSE is a command line ("docker compose")
  ${MUXCORE_COMPOSE:-docker compose} "${files[@]}" "$@"
}

registry_smoke_compose_project() {
  local name
  name="$(registry_smoke_compose config --format '{{.Name}}' 2>/dev/null || true)"
  [[ -n "$name" ]] || name="muxcore-mvp-registry"
  printf '%s' "$name"
}

registry_smoke_stack_running() {
  local id
  id="$(registry_smoke_compose ps -q core 2>/dev/null | head -1 || true)"
  [[ -n "$id" ]]
}

registry_smoke_network() {
  printf '%s_muxcore' "$(registry_smoke_compose_project)"
}

# curl from inside the compose network (for ports that are not host-published).
registry_smoke_curl() {
  registry_smoke_cli run --rm --network "$(registry_smoke_network)" "$REGISTRY_SMOKE_CURL_IMAGE" "$@"
}

registry_smoke_volume() {
  printf '%s_%s' "$(registry_smoke_compose_project)" "$1"
}

registry_smoke_should_use() {
  case "${MUXCORE_SMOKE_REGISTRY:-}" in
    1|true|yes) return 0 ;;
    0|false|no) return 1 ;;
  esac
  if command -v go >/dev/null 2>&1; then
    if (cd "${registry_smoke_root}" && go build -o /dev/null ./cmd/listmodules >/dev/null 2>&1); then
      return 1
    fi
  fi
  registry_smoke_stack_running
}

registry_smoke_enable() {
  export MUXCORE_SMOKE_REGISTRY=1
  export MUXCORE_MESH_ADDR="${MUXCORE_MESH_ADDR:-core:9090}"
  export MOVIES_GRPC_ADDR="${MOVIES_GRPC_ADDR:-media-movies:9420}"
  export TVSHOWS_GRPC_ADDR="${TVSHOWS_GRPC_ADDR:-media-tvshows:9440}"
  export ROOTS_GRPC_ADDR="${ROOTS_GRPC_ADDR:-media-root-folders:9540}"
  export AUTH_GRPC_ADDR="${AUTH_GRPC_ADDR:-auth-local:9403}"
  export SCANNER_GRPC_CLIENT_ADDR="${SCANNER_GRPC_CLIENT_ADDR:-media-scanner:9470}"
  export AUTOMATION_GRPC_CLIENT_ADDR="${AUTOMATION_GRPC_CLIENT_ADDR:-media-automation:9460}"
  export HEALTH_MONITOR_GRPC_CLIENT_ADDR="${HEALTH_MONITOR_GRPC_CLIENT_ADDR:-health-monitor:9202}"
  export SMOKE_HEALTH_MONITOR_STATUS="${SMOKE_HEALTH_MONITOR_STATUS:-http://health-monitor:9203/status}"
  export JELLYFIN_GRPC_CLIENT_ADDR="${JELLYFIN_GRPC_CLIENT_ADDR:-jellyfin-bridge:9475}"
  export MVP_DOWNLOADS_DIR="${MVP_DOWNLOADS_DIR:-/data/downloads}"
  export MVP_LIBRARY_ROOT="${MVP_LIBRARY_ROOT:-/data/movies}"
  export MVP_TV_LIBRARY_ROOT="${MVP_TV_LIBRARY_ROOT:-/data/shows}"
}

# Core and the modules do not serve gRPC reflection: grpcurl reads the service
# descriptors from proto/smoke.protoset (generated by cmd/smokeprotoset from the
# modules' Go packages; scripts/check-smoke-protoset_test.sh keeps it in sync).
REGISTRY_SMOKE_PROTOSET="smoke.protoset"

# ---- mesh TLS (household profile, ADR-0016/0017) ----
# In household every gRPC hop is TLS against core's CA and modules expect a
# client certificate, so the smoke enrolls a client identity of its own
# (MUXCORE_SMOKE_CLIENT_ID, default mvp-smoke) with a single-use token derived
# from MUXCORE_ENROLL_SECRET (scripts/gen-enrollment.sh --print-token), and
# keeps it in MUXCORE_SMOKE_ID_DIR (default run/smoke-id; reused while it
# verifies against the stack's CA). The public CA comes from the mesh-ca volume.
# MUXCORE_SMOKE_TLS=1|0 forces TLS on/off; default: read the running core's
# profile (dev + insecure flag = plaintext, docker-compose.dev.yml).
REGISTRY_SMOKE_CLIENT_ID="${MUXCORE_SMOKE_CLIENT_ID:-mvp-smoke}"
registry_smoke_tls_state=""

registry_smoke_id_dir() {
  printf '%s' "${MUXCORE_SMOKE_ID_DIR:-${registry_smoke_root}/run/smoke-id}"
}

# registry_smoke_tls_enabled — 0 (true) when the stack runs mesh TLS.
registry_smoke_tls_enabled() {
  if [[ -z "$registry_smoke_tls_state" ]]; then
    case "${MUXCORE_SMOKE_TLS:-auto}" in
      1|true|yes) registry_smoke_tls_state=1 ;;
      0|false|no) registry_smoke_tls_state=0 ;;
      *)
        local id env_lines=""
        id="$(registry_smoke_compose ps -q core 2>/dev/null | head -1 || true)"
        if [[ -n "$id" ]]; then
          env_lines="$(registry_smoke_cli inspect -f '{{range .Config.Env}}{{println .}}{{end}}' "$id" 2>/dev/null || true)"
        fi
        if grep -Eqx 'MUXCORE_INSECURE_DISABLE_TLS=(true|1)' <<<"$env_lines"; then
          registry_smoke_tls_state=0
        else
          registry_smoke_tls_state=1  # household is the default (ADR-0016)
        fi
        ;;
    esac
  fi
  [[ "$registry_smoke_tls_state" == 1 ]]
}

# registry_smoke_ca_file — host path of the stack's public CA (copied out of the
# mesh-ca volume; refreshed on every call so a recreated stack is picked up).
registry_smoke_ca_file() {
  local dir ca
  dir="$(registry_smoke_id_dir)"
  ca="$dir/ca.crt"
  (umask 077 && mkdir -p "$dir")
  if registry_smoke_cli run --rm -v "$(registry_smoke_volume mesh-ca):/m:ro"       "$REGISTRY_SMOKE_ALPINE_IMAGE" cat /m/ca.crt >"$ca.new" 2>/dev/null && [[ -s "$ca.new" ]]; then
    mv -f "$ca.new" "$ca"
  else
    rm -f "$ca.new"
    [[ -s "$ca" ]] || { echo "FAIL: no core CA in volume $(registry_smoke_volume mesh-ca) (core not started?)" >&2; return 1; }
  fi
  printf '%s' "$ca"
}

# registry_smoke_core_url — core HTTP base URL from the host (HTTPS in household).
registry_smoke_core_url() {
  if registry_smoke_tls_enabled; then printf 'https://127.0.0.1:%s' "${MUXCORE_HTTP_PORT:-8080}"
  else printf 'http://127.0.0.1:%s' "${MUXCORE_HTTP_PORT:-8080}"; fi
}

registry_smoke_enroll_token() {
  if [[ -n "${MUXCORE_SMOKE_ENROLL_TOKEN:-}" ]]; then
    printf '%s' "$MUXCORE_SMOKE_ENROLL_TOKEN"
    return
  fi
  "${registry_smoke_root}/scripts/gen-enrollment.sh" --print-token "$REGISTRY_SMOKE_CLIENT_ID"
}

# registry_smoke_ensure_identity — the smoke's client certificate (household).
registry_smoke_ensure_identity() {
  local dir ca key crt csr token payload resp signed
  dir="$(registry_smoke_id_dir)"
  ca="$(registry_smoke_ca_file)" || return 1
  key="$dir/module.key" crt="$dir/module.crt" csr="$dir/module.csr"
  if [[ -s "$key" && -s "$crt" ]] && openssl verify -CAfile "$ca" "$crt" >/dev/null 2>&1; then
    return 0
  fi
  command -v openssl >/dev/null 2>&1 || { echo "FAIL: openssl is required for the household smoke identity" >&2; return 1; }
  echo "==> smoke client: enrolling mesh identity ${REGISTRY_SMOKE_CLIENT_ID} (ADR-0017)"
  rm -f "$key" "$crt" "$csr"
  (umask 077 && openssl ecparam -name prime256v1 -genkey -noout | openssl pkcs8 -topk8 -nocrypt -out "$key") || return 1
  openssl req -new -key "$key" -subj "/CN=${REGISTRY_SMOKE_CLIENT_ID}" -out "$csr" 2>/dev/null || return 1
  token="$(registry_smoke_enroll_token)" || return 1
  payload="$(jq -cn --arg t "$token" --arg id "$REGISTRY_SMOKE_CLIENT_ID" --rawfile csr "$csr"     '{token: $t, module_id: $id, csr_pem: $csr}')"
  # Server-verified TLS without a client certificate: the token is the credential.
  resp="$(REGISTRY_SMOKE_GRPCURL_NO_CERT=1 registry_smoke_grpcurl "${MUXCORE_MESH_ADDR:-core:9090}"     -d "$payload" muxcore.module.v1.ModuleRegistration/BootstrapRegister)" || return 1
  signed="$(jq -r '.signedCert // .signed_cert // empty' <<<"$resp")"
  if [[ "$(jq -r '.accepted // false' <<<"$resp")" != true || -z "$signed" ]]; then
    echo "FAIL: smoke client enrollment rejected: $(jq -c 'del(.signedCert, .caCert)' <<<"$resp" 2>/dev/null || echo "$resp")" >&2
    echo "      (token already used? ${MUXCORE_COMPOSE:-docker compose} exec core ./muxcored enroll reset ${REGISTRY_SMOKE_CLIENT_ID})" >&2
    return 1
  fi
  printf '%s\n' "$signed" >"$crt"
  rm -f "$csr"
  openssl verify -CAfile "$ca" "$crt" >/dev/null || { echo "FAIL: enrolled smoke certificate does not verify" >&2; return 1; }
  echo "OK smoke client identity enrolled ($crt)"
}

# Container args + grpcurl flags for the transport: -plaintext (dev), else TLS
# with core's CA and (unless REGISTRY_SMOKE_GRPCURL_NO_CERT=1) the smoke
# identity. The grpcurl image runs as a non-root user that cannot read the 0600
# key, so it runs as root (= the invoking user under rootless podman).
registry_smoke_grpcurl_transport() {
  registry_smoke_grpcurl_run_args=()
  registry_smoke_grpcurl_tls_flags=()
  if ! registry_smoke_tls_enabled; then
    registry_smoke_grpcurl_tls_flags=(-plaintext)
    return 0
  fi
  registry_smoke_grpcurl_run_args=(-v "$(registry_smoke_volume mesh-ca):/mesh-ca:ro")
  registry_smoke_grpcurl_tls_flags=(-cacert /mesh-ca/ca.crt)
  if [[ "${REGISTRY_SMOKE_GRPCURL_NO_CERT:-}" != 1 ]]; then
    registry_smoke_ensure_identity || return 1
    registry_smoke_grpcurl_run_args+=(--user 0:0 -v "$(registry_smoke_id_dir):/smoke-id:ro")
    registry_smoke_grpcurl_tls_flags+=(-cert /smoke-id/module.crt -key /smoke-id/module.key)
  fi
}

# registry_smoke_grpcurl_on <network> <addr> [grpcurl flags...] <method>
registry_smoke_grpcurl_on() {
  local net="$1" addr="$2"
  shift 2
  local method="${*: -1}"
  local -a flags=("${@:1:$#-1}")
  registry_smoke_grpcurl_transport || return 1
  registry_smoke_cli run --rm --network "$net" \
    -v "${registry_smoke_root}/proto:/proto:ro" "${registry_smoke_grpcurl_run_args[@]}" \
    "$REGISTRY_SMOKE_GRPCURL_IMAGE" \
    "${registry_smoke_grpcurl_tls_flags[@]}" -protoset "/proto/${REGISTRY_SMOKE_PROTOSET}" "${flags[@]}" "$addr" "$method"
}

# registry_smoke_grpcurl <addr> [flags...] <method> — on the compose network.
registry_smoke_grpcurl() {
  registry_smoke_grpcurl_on "$(registry_smoke_network)" "$@"
}

registry_smoke_grpcurl_host() {
  registry_smoke_grpcurl_on host "$@"
}

registry_smoke_resolve_ok() {
  local mod="$1"
  local out
  out="$(registry_smoke_grpcurl "${MUXCORE_MESH_ADDR:-core:9090}" \
    -d "{\"module_id\":\"${mod}\"}" \
    muxcore.discovery.v1.DiscoveryService/Resolve 2>/dev/null || true)"
  [[ -n "$out" ]] && grep -Eq '"found"[[:space:]]*:[[:space:]]*true' <<<"$out"
}

registry_smoke_cmd_listmodules() {
  local need=(
    api-rest auth-local database-sqlite secrets-file encryption-aesgcm
    call-policy-default publish-policy-default metadata-tmdb media-movies
    media-tvshows media-automation media-scanner media-root-folders
    request-media notification-default
  )
  if [[ -n "${SMOKE_MODULES:-}" ]]; then
    IFS=',' read -ra need <<<"$SMOKE_MODULES"
  fi
  local id missing=0
  for id in "${need[@]}"; do
    id="${id// /}"
    [[ -z "$id" ]] && continue
    if registry_smoke_resolve_ok "$id"; then
      echo "OK $id"
    else
      echo "MISSING $id" >&2
      missing=$((missing + 1))
    fi
  done
  [[ "$missing" -eq 0 ]]
}

registry_smoke_cmd_gettoken() {
  local addr="127.0.0.1:9403" user pass out
  user="admin"
  pass=""
  out=""
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -addr) addr="$2"; shift 2 ;;
      -user) user="$2"; shift 2 ;;
      -password) pass="$2"; shift 2 ;;
      -out) out="$2"; shift 2 ;;
      *) shift ;;
    esac
  done
  [[ -n "$pass" ]] || { echo "FAIL: -password required" >&2; return 1; }
  local host_addr="$addr"
  if [[ "$host_addr" != *:* ]]; then
    host_addr="127.0.0.1:${host_addr}"
  fi
  if [[ "$host_addr" == auth-local:* ]]; then
    host_addr="127.0.0.1:9403"
  fi
  local cred_payload resp token
  cred_payload="$(USER="$user" PASS="$pass" python3 - <<'PY'
import json, os
print(json.dumps({"username": os.environ["USER"], "password": os.environ["PASS"]}))
PY
)"
  # credential_data is `bytes` (JSON credentials): base64 in grpcurl's JSON.
  resp="$(registry_smoke_grpcurl_host "$host_addr" \
    -d "$(CRED="$cred_payload" python3 -c 'import base64, json, os
print(json.dumps({"credential_type": "password", "credential_data": base64.b64encode(os.environ["CRED"].encode()).decode()}))')" \
    muxcore.auth.v1.AuthService/Authenticate)"
  token="$(printf '%s' "$resp" | python3 -c 'import json,sys
d=json.load(sys.stdin)
print(d.get("sessionToken") or d.get("session_token") or "")' 2>/dev/null || true)"
  [[ -n "$token" ]] || { echo "FAIL: auth token empty: $resp" >&2; return 1; }
  if [[ -n "$out" ]]; then
    mkdir -p "$(dirname "$out")"
    printf '%s\n' "$token" >"$out"
  else
    printf '%s\n' "$token"
  fi
}

registry_smoke_cmd_addmovie() {
  local addr="$MOVIES_GRPC_ADDR" root="$MVP_LIBRARY_ROOT"
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -addr) addr="$2"; shift 2 ;;
      -root) root="$2"; shift 2 ;;
      *) shift ;;
    esac
  done
  if [[ -n "$root" ]]; then
    registry_smoke_grpcurl "${ROOTS_GRPC_ADDR:-media-root-folders:9540}" \
      -d "{\"path\":\"${root}\",\"name\":\"Movies\",\"media_kind\":\"movies\"}" \
      muxcore.roots.v1.RootFolderService/CreateRoot >/dev/null 2>&1 || true
  fi
  registry_smoke_grpcurl "$addr" \
    -d "{\"tmdb_id\":550,\"title\":\"Fight Club\",\"year\":1999,\"root_folder_path\":\"${root}\"}" \
    muxcore.media.movies.v1.MovieManagementService/AddMovie
  registry_smoke_grpcurl "$addr" \
    -d '{}' \
    muxcore.media.movies.v1.MovieManagementService/ListMovies >/dev/null
  echo "OK addmovie (registry grpcurl)"
}

registry_smoke_cmd_addtvshow() {
  local addr="$TVSHOWS_GRPC_ADDR" root="$MVP_TV_LIBRARY_ROOT"
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -addr) addr="$2"; shift 2 ;;
      -root) root="$2"; shift 2 ;;
      *) shift ;;
    esac
  done
  if [[ -n "$root" ]]; then
    registry_smoke_grpcurl "${ROOTS_GRPC_ADDR:-media-root-folders:9540}" \
      -d "{\"path\":\"${root}\",\"name\":\"TV\",\"media_kind\":\"tv\"}" \
      muxcore.roots.v1.RootFolderService/CreateRoot >/dev/null 2>&1 || true
  fi
  registry_smoke_grpcurl "$addr" \
    -d "{\"tmdb_id\":1396,\"name\":\"Breaking Bad\",\"year\":2008,\"root_folder_path\":\"${root}\"}" \
    muxcore.media.tv.v1.TvManagementService/AddTVShow
  registry_smoke_grpcurl "$addr" \
    -d '{}' \
    muxcore.media.tv.v1.TvManagementService/ListTVShows >/dev/null
  echo "OK addtvshow (registry grpcurl)"
}

registry_smoke_cmd_importscan() {
  local addr="$SCANNER_GRPC_CLIENT_ADDR"
  local watch="$MVP_DOWNLOADS_DIR" library="$MVP_LIBRARY_ROOT"
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -addr) addr="$2"; shift 2 ;;
      -watch) watch="$2"; shift 2 ;;
      -library) library="$2"; shift 2 ;;
      *) shift ;;
    esac
  done
  local vol_dl vol_mov
  vol_dl="$(registry_smoke_volume downloads)"
  vol_mov="$(registry_smoke_volume movies)"
  # 6 MiB: above media-scanner's default 5 MiB video floor (SCANNER_MIN_VIDEO_BYTES),
  # which the registry compose keeps (run-host.sh sets it to 0).
  registry_smoke_cli run --rm \
    -v "${vol_dl}:/data/downloads" \
    -v "${vol_mov}:/data/movies" \
    "$REGISTRY_SMOKE_ALPINE_IMAGE" sh -c 'mkdir -p "/data/downloads/Fight.Club.1999.1080p.BluRay.x264" && dd if=/dev/zero of="/data/downloads/Fight.Club.1999.1080p.BluRay.x264/Fight.Club.1999.1080p.BluRay.mkv" bs=1048576 count=6 status=none'
  registry_smoke_grpcurl "$addr" \
    -d "{\"path\":\"${watch}\",\"library_path\":\"${library}\",\"media_type\":\"movie\"}" \
    muxcore.scanner.v1.ScannerService/AddWatchDir >/dev/null 2>&1 || true
  registry_smoke_grpcurl "$addr" \
    -d "{\"path\":\"${watch}/Fight.Club.1999.1080p.BluRay.x264\"}" \
    muxcore.scanner.v1.ScannerService/ImportPath
  echo "OK importscan (registry grpcurl)"
}

registry_smoke_cmd_automationqueue() {
  local addr="$AUTOMATION_GRPC_CLIENT_ADDR"
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -addr) addr="$2"; shift 2 ;;
      *) shift ;;
    esac
  done
  registry_smoke_grpcurl "$addr" \
    -d '{"item_type":"movie","item_id":"mv_smoke_550","tmdb_id":550,"title":"Fight Club","year":1999}' \
    muxcore.automation.v1.AutomationService/AddToQueue
  registry_smoke_grpcurl "$addr" \
    -d '{"page":1,"page_size":50,"filter":"movie"}' \
    muxcore.automation.v1.AutomationService/GetQueue >/dev/null
  echo "OK automationqueue (registry grpcurl)"
}

registry_smoke_cmd_healthreport() {
  local addr="$HEALTH_MONITOR_GRPC_CLIENT_ADDR" status_url="$SMOKE_HEALTH_MONITOR_STATUS"
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -addr) addr="$2"; shift 2 ;;
      -status-url) status_url="$2"; shift 2 ;;
      *) shift ;;
    esac
  done
  registry_smoke_grpcurl "$addr" \
    -d '{"modules":[{"module_id":"mvp-smoke","state":"running"},{"module_id":"api-rest","state":"running"}]}' \
    muxcore.healthmonitor.v1.HealthMonitorService/ReportHealth
  registry_smoke_grpcurl "$addr" \
    -d '{"event_type":"health.smoke","module_id":"mvp-smoke","message":"health-monitor smoke"}' \
    muxcore.healthmonitor.v1.HealthMonitorService/PublishEvent
  # running -> degraded transition: health-monitor fans module.degraded out on the
  # mesh (as cmd/healthreport does), which admin-ui /events must show.
  registry_smoke_grpcurl "$addr" \
    -d '{"modules":[{"module_id":"mvp-smoke","state":"degraded","error":"mvp smoke degraded"}]}' \
    muxcore.healthmonitor.v1.HealthMonitorService/ReportHealth
  local hm_auth=()
  if [[ -n "${HEALTH_MONITOR_HTTP_TOKEN:-}" ]]; then
    hm_auth=(-H "Authorization: Bearer ${HEALTH_MONITOR_HTTP_TOKEN}")
  fi
  registry_smoke_curl -sf "${hm_auth[@]}" "$status_url" >/dev/null
  echo "OK healthreport (registry grpcurl)"
}

registry_smoke_cmd_jellyfinstatus() {
  local addr="$JELLYFIN_GRPC_CLIENT_ADDR"
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -addr) addr="$2"; shift 2 ;;
      -require-configured) shift ;;
      *) shift ;;
    esac
  done
  registry_smoke_grpcurl "$addr" \
    -d '{}' \
    muxcore.playback.jellyfin.v1.JellyfinBridge/Status
  echo "OK jellyfinstatus (registry grpcurl)"
}

registry_smoke_cmd_jellyfinlink() {
  local addr="$JELLYFIN_GRPC_CLIENT_ADDR"
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -addr) addr="$2"; shift 2 ;;
      -webhook-url) shift 2 ;;
      *) shift ;;
    esac
  done
  registry_smoke_grpcurl "$addr" \
    -d '{"link":{"muxcore_id":"mv_smoke_550","jellyfin_id":"jf-smoke-fixture","path":"/library/Movies/Fight Club (1999)/Fight Club.mkv","media_kind":"movie","title":"Fight Club","provider_ids":{"Tmdb":"550"}}}' \
    muxcore.playback.jellyfin.v1.JellyfinBridge/UpsertItemLink
  echo "OK jellyfinlink (registry grpcurl)"
}

registry_smoke_cmd_jellyfinlive() {
  echo "OK jellyfinlive skipped (registry soft verify)"
}

registry_smoke_cmd_mediarequest() {
  local base="http://127.0.0.1:5173" jar="" require=0
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -base) base="$2"; shift 2 ;;
      -cookie-jar) jar="$2"; shift 2 ;;
      -require-search) require=1; shift ;;
      *) shift ;;
    esac
  done
  [[ -n "$jar" ]] || { echo "FAIL: mediarequest needs -cookie-jar in registry mode" >&2; return 1; }
  local curl_auth=(-b "$jar" -c "$jar")
  local search_body code
  search_body="$(curl -sf "${curl_auth[@]}" "${base}/api/search?q=Fight+Club")"
  if [[ "$require" -eq 1 ]]; then
    grep -qi 'Fight Club\|"id"' <<<"$search_body" || {
      echo "FAIL: search (require-search): $search_body" >&2
      return 1
    }
  fi
  # POST as a non-browser API client (bearer, no cookie) so the BFF CSRF
  # Origin check does not apply (NFR-SEC-004).
  local session_tok
  session_tok="$(awk -F'\t' '$6 == "session" { v = $7 } END { print v }' "$jar")"
  local post_auth=("${curl_auth[@]}")
  if [[ -n "$session_tok" ]]; then
    post_auth=(-H "Authorization: Bearer ${session_tok}")
  fi
  code="$(curl -sf "${post_auth[@]}" -o /tmp/mvp-registry-request.json -w '%{http_code}' \
    -X POST "${base}/api/request" \
    -H 'Content-Type: application/json' \
    -d '{"tmdbId":550,"title":"Fight Club","year":1999,"overview":"MVP smoke request","poster":""}')"
  [[ "$code" == "200" ]] || { echo "FAIL: POST /api/request HTTP $code" >&2; return 1; }
  curl -sf "${curl_auth[@]}" "${base}/api/requests" | grep -qi 'Fight Club\|request' || {
    echo "FAIL: GET /api/requests missing fixture" >&2
    return 1
  }
  echo "OK request-media via media-ui (registry curl)"
}

# registry_smoke_backupctl_args <cmd> [flags] — translate cmd/backupctl flags into
# "<Method>\t<json>" for BackupService (no reflection: grpcurl uses the vendored
# proto/muxcore/backup/v1/backup.proto, a copy of backup-local's).
registry_smoke_backupctl_args() {
  local cmd="${1:-}"
  shift || true
  local id="" target="" restore_test=false
  local -a sources=()
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -id) id="${2:-}"; shift 2 ;;
      -target) target="${2:-}"; shift 2 ;;
      -restore-test) restore_test=true; shift ;;
      -source) sources+=("${2:-}"); shift 2 ;;
      *) echo "backupctl: unknown flag $1" >&2; return 2 ;;
    esac
  done
  case "$cmd" in
    create) printf 'CreateBackup\t%s\n' "$(jq -cn '{source_paths: $ARGS.positional}' --args "${sources[@]}")" ;;
    verify)
      [[ -n "$id" ]] || { echo "backupctl: verify: -id is required" >&2; return 2; }
      printf 'VerifyBackup\t%s\n' "$(jq -cn --arg id "$id" --argjson rt "$restore_test" '{backup_id: $id, restore_test: $rt}')" ;;
    restore)
      [[ -n "$id" && -n "$target" ]] || { echo "backupctl: restore: -id and -target are required" >&2; return 2; }
      printf 'RestoreBackup\t%s\n' "$(jq -cn --arg id "$id" --arg t "$target" '{backup_id: $id, target_path: $t}')" ;;
    list) printf 'ListBackups\t{}\n' ;;
    *) echo "backupctl: unknown command ${cmd:-<none>}" >&2; return 2 ;;
  esac
}

# registry_smoke_cmd_backupctl [-addr host:port] <create|verify|restore|list> [flags]
# Same CLI and JSON output shape as cmd/backupctl, via containerized grpcurl on
# the compose network (backup-local:9302 by default).
registry_smoke_cmd_backupctl() {
  local addr="${BACKUP_GRPC_CLIENT_ADDR:-backup-local:9302}"
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -addr) addr="$2"; shift 2 ;;
      -timeout) shift 2 ;;
      *) break ;;
    esac
  done
  local spec method data
  spec="$(registry_smoke_backupctl_args "$@")" || return $?
  method="${spec%%$'\t'*}"
  data="${spec#*$'\t'}"
  registry_smoke_grpcurl_transport || return 1
  registry_smoke_cli run --rm --network "$(registry_smoke_network)" \
    -v "${registry_smoke_root}/proto:/proto:ro" "${registry_smoke_grpcurl_run_args[@]}" \
    "$REGISTRY_SMOKE_GRPCURL_IMAGE" \
    "${registry_smoke_grpcurl_tls_flags[@]}" -max-time 600 -import-path /proto -proto muxcore/backup/v1/backup.proto \
    -d "$data" "$addr" "muxcore.backup.v1.BackupService/${method}"
}

registry_smoke_cmd() {
  local cmd="$1"
  shift
  case "$cmd" in
    listmodules) registry_smoke_cmd_listmodules "$@" ;;
    gettoken) registry_smoke_cmd_gettoken "$@" ;;
    addmovie) registry_smoke_cmd_addmovie "$@" ;;
    addtvshow) registry_smoke_cmd_addtvshow "$@" ;;
    importscan) registry_smoke_cmd_importscan "$@" ;;
    automationqueue) registry_smoke_cmd_automationqueue "$@" ;;
    acquirefixture) registry_smoke_cmd_acquirefixture "$@" ;;  # scripts/lib/acquisition-smoke.sh
    healthreport) registry_smoke_cmd_healthreport "$@" ;;
    jellyfinstatus) registry_smoke_cmd_jellyfinstatus "$@" ;;
    jellyfinlink) registry_smoke_cmd_jellyfinlink "$@" ;;
    jellyfinlive) registry_smoke_cmd_jellyfinlive "$@" ;;
    mediarequest) registry_smoke_cmd_mediarequest "$@" ;;
    backupctl) registry_smoke_cmd_backupctl "$@" ;;
    authctl)
      echo "OK authctl skipped (AUTH_BOOTSTRAP_* in registry compose)"
      ;;
    *)
      echo "FAIL: unknown registry smoke cmd: $cmd" >&2
      return 1
      ;;
  esac
}

registry_smoke_bootstrap_auth() {
  local user pass token_file auth_addr
  user="${MVP_ADMIN_USER:-admin}"
  pass="${MVP_ADMIN_PASSWORD:?MVP_ADMIN_PASSWORD is not set (set it in .env; no default)}"
  token_file="${MVP_TOKEN_FILE:-${registry_smoke_root}/run/admin.token}"
  auth_addr="${AUTH_GRPC_ADDR:-auth-local:9403}"
  mkdir -p "$(dirname "$token_file")"
  echo "==> registry bootstrap: AUTH_BOOTSTRAP in compose + grpcurl token"
  local host_auth="127.0.0.1:9403"
  if [[ "$auth_addr" == *":"* && "$auth_addr" != 127.0.0.1:* && "$auth_addr" != localhost:* ]]; then
    host_auth="127.0.0.1:9403"
  else
    host_auth="$auth_addr"
  fi
  registry_smoke_cmd_gettoken -addr "$host_auth" -user "$user" -password "$pass" -out "$token_file"
  echo "token written to $token_file"
}
